apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apps
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'git@github.com:patriciocostilla/gitops-bootstrap.git'
    path: cluster-core-services
    targetRevision: main
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: cluster-core-services
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
