apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    chart: ingress-nginx
    repoURL: 'https://kubernetes.github.io/ingress-nginx'
    targetRevision: {{ .Values.ingressNginx.version | default "4.4.2" }}
    helm:
        releaseName: ingress-nginx
        values: |
          controller:
            extraArgs:
              enable-ssl-passthrough: true
            config:
              enable-modsecurity: "false"
              enable-owasp-modsecurity-crs: "false"
              modsecurity-snippet: |
                SecRuleEngine On
                SecAuditLog /dev/stdout
                SecAuditLogFormat JSON
                SecAuditEngine On  
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: ingress-nginx
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
